// ========== 已确认方案 A：患者、AI 与管理端统一工作流 ==========
const WUtil = {
  escape(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); },
  statusClass(status) { return status==='待处理'?'pending':status==='已分配'?'accepted':status==='服务中'?'serving':status==='已取消'?'cancelled':'done'; },
  value(id) { return document.getElementById(id)?.value?.trim() || ''; },
  closeSheet(id) { document.getElementById(id)?.remove(); },
  sheet(id, title, body, actions='') {
    this.closeSheet(id);
    const mask=document.createElement('div'); mask.id=id; mask.className='workflow-sheet-mask';
    mask.innerHTML=`<section class="workflow-sheet" role="dialog" aria-modal="true" aria-labelledby="${id}_title"><header><h2 id="${id}_title">${this.escape(title)}</h2><button class="icon-button" aria-label="关闭" onclick="WUtil.closeSheet('${id}')">×</button></header><div class="workflow-sheet-body">${body}</div>${actions?`<footer>${actions}</footer>`:''}</section>`;
    document.body.appendChild(mask); setTimeout(()=>mask.classList.add('show'),0); return mask;
  },
  imageGrid(images, removeCall='') {
    if (!images?.length) return '<div class="helper-text">暂无图片</div>';
    return `<div class="media-grid">${images.map((img,i)=>`<figure><img src="${img.dataUrl}" alt="${this.escape(img.name)}" loading="lazy" /><figcaption>${this.escape(img.name)}</figcaption>${removeCall?`<button class="media-remove" aria-label="删除 ${this.escape(img.name)}" onclick="${removeCall}(${i})">×</button>`:''}</figure>`).join('')}</div>`;
  },
};

// ---- 患者端应用外框：通知、AI 抽屉和稳定交互 ----
const _legacyRenderPatientApp = App.renderPatientApp.bind(App);
App.renderPatientApp = function(root) {
  _legacyRenderPatientApp(root);
  const exit=document.querySelector('.role-btn');
  if (exit) {
    const unread=CareStore.notificationsFor('patient').filter(n=>!n.read).length;
    exit.insertAdjacentHTML('beforebegin', `<button class="patient-notify-button" aria-label="患者通知${unread?`，${unread}条未读`:''}" onclick="App.togglePatientNotifications()">${P_ICON.inbox}${unread?`<span>${unread}</span>`:''}</button>`);
  }
  const panel=document.getElementById('aiPanel');
  if (panel) {
    panel.setAttribute('role','dialog'); panel.setAttribute('aria-label','智能陪诊助理');
    panel.innerHTML=`
      <header class="ai-panel-head"><div><strong>智能陪诊助理</strong><span>信息由您确认后才会提交</span></div><button class="icon-button" id="aiClose" aria-label="关闭智能助手">×</button></header>
      <div class="ai-stage" id="aiStage"></div>
      <div class="ai-panel-body" id="aiMessages" aria-live="polite"></div>
      <div class="ai-quick"><button data-q="下周二去协和看心内科，全程陪诊">描述陪诊需求</button><button data-q="服务怎么收费">查看收费</button><button data-q="我的需求进度">查询进度</button></div>
      <div class="ai-input"><label class="sr-only" for="aiInput">输入陪诊需求</label><input id="aiInput" type="text" autocomplete="off" placeholder="例如：下周二去协和看心内科" /><button id="aiSend">发送</button></div>`;
    document.getElementById('aiClose').onclick=()=>App.closeAI();
    document.getElementById('aiSend').onclick=()=>App.aiSend();
    document.getElementById('aiInput').onkeydown=e=>{if(e.key==='Enter')App.aiSend();};
    panel.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{document.getElementById('aiInput').value=b.dataset.q;App.aiSend();});
    App.renderAiConversation();
  }
};

App.closeAI = function() { const panel=document.getElementById('aiPanel'); if(panel)panel.hidden=true; const ball=document.getElementById('aiFloat'); if(ball)ball.hidden=false; if(this.state==='patient'&&this.patientTab===1)this.renderPatientScreen(); };
App.openAI = function() { const panel=document.getElementById('aiPanel'); if(!panel)return; panel.hidden=false; document.getElementById('aiFloat').hidden=true; this.renderAiConversation(); setTimeout(()=>document.getElementById('aiInput')?.focus(),100); };
App.aiAdd = function(role, html, action='') {
  CareStore.state.ai.messages.push({ id:CareStore.uid('AIM'), role, html, action, time:CareStore.now() });
  CareStore.state.ai.messages=CareStore.state.ai.messages.slice(-30); CareStore.save(); this.renderAiConversation();
};
App.aiCard = function(stage) {
  const d=CareStore.draft(), price=PriceTable.items.find(p=>p.name===d.serviceType);
  if(stage==='confirm_details') return `<div class="ai-action-card"><h4>请确认陪诊信息</h4><dl><div><dt>医院</dt><dd>${WUtil.escape(d.hospital)}</dd></div><div><dt>科室</dt><dd>${WUtil.escape(d.dept)}</dd></div><div><dt>日期</dt><dd>${WUtil.escape(d.date)}</dd></div><div><dt>服务</dt><dd>${WUtil.escape(d.serviceType)}</dd></div></dl><div class="ai-card-actions"><button onclick="App.aiAction('confirm-details')">信息正确</button><button class="secondary" onclick="App.aiAction('edit-form')">去表单修改</button></div></div>`;
  if(stage==='upload_identity') return `<div class="ai-action-card"><h4>身份证资料（可稍后补充）</h4><p>仅用于实名认证。演示 OCR 结果仍需您人工确认。</p><div class="ai-card-actions"><button onclick="App.aiAction('goto-identity')">上传身份证</button><button class="secondary" onclick="App.aiAction('skip-identity')">稍后补充</button></div></div>`;
  if(stage==='upload_reports') return `<div class="ai-action-card"><h4>检查报告（可选）</h4><p>可上传近期检查报告，帮助陪诊人员提前了解情况。</p><div class="ai-card-actions"><button onclick="App.aiAction('goto-reports')">上传报告</button><button class="secondary" onclick="App.aiAction('skip-reports')">暂不上传</button></div></div>`;
  if(stage==='final_confirm') return `<div class="ai-action-card price-confirm"><h4>提交前确认</h4><div class="price-line"><span>${WUtil.escape(d.serviceType)}</span><strong>¥${price?.price || 0}<small>/${WUtil.escape(price?.unit||'次')}</small></strong></div><p>提交后后台将收到提醒并安排陪诊师。身份证和医疗图片属于敏感资料。</p><div class="ai-card-actions"><button onclick="App.aiAction('submit')">确认提交</button><button class="secondary" onclick="App.aiAction('edit-form')">返回修改</button></div></div>`;
  return '';
};
App.renderAiConversation = function() {
  const body=document.getElementById('aiMessages'), stage=document.getElementById('aiStage'); if(!body)return;
  const ai=CareStore.state.ai;
  const labels={idle:'开始',collecting:'收集信息',confirm_details:'确认信息',upload_identity:'身份证',upload_reports:'检查报告',final_confirm:'确认提交',submitted:'已提交'};
  stage.innerHTML=`<span>当前步骤</span><strong>${labels[ai.stage]||'开始'}</strong>`;
  const welcome=`<div class="ai-msg ai-bot">您好，我会一次只问一个问题，并把内容同步到人工表单。您确认前不会提交。</div>`;
  body.innerHTML=welcome+ai.messages.map(m=>`<div class="ai-msg ${m.role==='user'?'ai-user':'ai-bot'}">${m.role==='user'?WUtil.escape(m.html):m.html}</div>`).join('')+this.aiCard(ai.stage);
  body.querySelectorAll('button').forEach(b=>b.type='button'); body.scrollTop=body.scrollHeight;
};
App.aiSend = function() {
  const input=document.getElementById('aiInput'), q=input?.value.trim(); if(!q)return; input.value='';
  this.aiAdd('user',q);
  const result=AiAssistantService.interpret({ text:q, draft:CareStore.draft(), intent:CareStore.state.ai.stage });
  if(result.intent==='price_query') {
    const lines=PriceTable.items.filter(p=>p.active!==false).map(p=>`${WUtil.escape(p.name)}：¥${p.price}/${WUtil.escape(p.unit)}`).join('<br>');
    this.aiAdd('bot',`当前公开收费如下：<br>${lines}<br><small>最终费用以提交确认卡为准。</small>`); return;
  }
  if(result.intent==='hospital_query') { this.aiAdd('bot',`当前可选医院：<br>${CareStore.state.hospitals.filter(h=>h.active).map(h=>`• ${WUtil.escape(h.name)}：${WUtil.escape(h.intro)}`).join('<br>')}`); return; }
  if(result.intent==='progress_query') {
    const list=CareStore.state.needs.filter(n=>n.patientName===MockData.patient.user.name).slice(0,3);
    this.aiAdd('bot',list.length?list.map(n=>`• ${WUtil.escape(n.hospital)} · ${WUtil.escape(n.status)}`).join('<br>'):'您还没有提交过陪诊需求。'); return;
  }
  CareStore.patchDraft(result.fields); CareStore.state.ai.stage=result.missingFields.length?'collecting':'confirm_details'; CareStore.save();
  if(result.missingFields.length) {
    const prompts={hospital:'您想去哪家医院？',dept:'需要看哪个科室？',date:'希望哪天就诊？',serviceType:'需要半程、全程、复诊还是代办跑腿？'};
    this.aiAdd('bot',`我已经记下部分信息。${prompts[result.missingFields[0]]}`);
  } else {
    this.aiAdd('bot','信息已经整理好了，请查看确认卡。');
  }
};
App.aiAction = function(action) {
  if(action==='confirm-details'){CareStore.state.ai.stage='upload_identity';CareStore.save();this.renderAiConversation();return;}
  if(action==='skip-identity'){CareStore.state.ai.stage='upload_reports';CareStore.save();this.renderAiConversation();return;}
  if(action==='skip-reports'){CareStore.state.ai.stage='final_confirm';CareStore.save();this.renderAiConversation();return;}
  if(action==='goto-identity'||action==='goto-reports'||action==='edit-form'){
    this.closeAI(); this.switchTab(1); setTimeout(()=>document.getElementById(action==='goto-reports'?'report_section':action==='goto-identity'?'identity_section':'need_form')?.scrollIntoView({behavior:'smooth'}),100); return;
  }
  if(action==='submit'){
    try { const need=CareStore.createNeedFromDraft(); CareStore.state.ai.stage='submitted'; CareStore.save(); this.aiAdd('bot',`需求已提交成功，编号 <strong>${WUtil.escape(need.id)}</strong>。后台已收到提醒，您可在“陪诊进度”查看。`); }
    catch(error){this.aiAdd('bot',`暂时不能提交：${WUtil.escape(error.message)}。您可以返回表单修改。`);}
  }
};

App.togglePatientNotifications = function() {
  const existing=document.getElementById('patientNotifyPanel'); if(existing){existing.remove();return;}
  const list=CareStore.notificationsFor('patient');
  const panel=document.createElement('div'); panel.id='patientNotifyPanel'; panel.className='patient-notify-panel';
  panel.innerHTML=`<header><strong>我的提醒</strong><button onclick="App.markAllPatientNotifications()">全部已读</button></header>${list.length?list.map(n=>`<button class="patient-notify-item ${n.read?'':'unread'}" onclick="App.openPatientNotification('${n.id}')"><span>${WUtil.escape(n.title)}</span><small>${WUtil.escape(n.time)}</small></button>`).join(''):'<div class="empty-inline">暂无提醒</div>'}`;
  document.getElementById('app').appendChild(panel);
};
App.markAllPatientNotifications=function(){CareStore.markAllNotifications('patient');this.render();};
App.openPatientNotification=function(id){const n=CareStore.markNotification(id);document.getElementById('patientNotifyPanel')?.remove();if(n?.targetType==='need'&&CareStore.need(n.targetId)){this.switchTab(2);setTimeout(()=>Patient.openNeedDetail(n.targetId),0);}else{this.toast('对应记录不存在或已移除');}};

// ---- 患者端：共享草稿人工表单 ----
Patient.renderNeed = function(el) {
  const d=CareStore.draft(), u=MockData.patient.user, med=MockData.patient.medical;
  const hospitals=CareStore.state.hospitals.filter(h=>h.active);
  el.innerHTML=`<div id="need_form" class="page-head"><h2>我的需求</h2><div>AI 帮填和自己填写会实时同步，不会重复填写</div></div>
    <div class="path-switch" role="group" aria-label="需求填写方式"><button class="active" aria-pressed="true">自己填写</button><button onclick="App.openAI()">AI 帮我填写</button></div>
    <div class="draft-status">草稿已自动保存到本机浏览器</div>
    <section class="card"><div class="card-title">${P_ICON.user} 就诊人</div><div class="summary-grid"><div><span>姓名</span><strong>${WUtil.escape(u.name)}</strong></div><div><span>电话</span><strong>${WUtil.escape(u.phone)}</strong></div><div><span>病史</span><strong>${WUtil.escape(med.history)}</strong></div><div><span>行动能力</span><strong>${WUtil.escape(med.mobility)}</strong></div></div></section>
    <section class="card"><div class="card-title">${P_ICON.clipboard} 就诊与服务</div>
      <label class="field-label" for="req_hospital">希望就诊医院 <em>*</em></label><select class="fg-select draft-field" id="req_hospital" data-draft="hospital"><option value="">请选择医院</option>${hospitals.map(h=>`<option ${d.hospital===h.name?'selected':''}>${WUtil.escape(h.name)}</option>`).join('')}</select><button class="text-action" onclick="App.switchTab(3)">列表里没有？申请新医院</button>
      <label class="field-label" for="req_dept">就诊科室 <em>*</em></label><input class="fg-input draft-field" id="req_dept" data-draft="dept" value="${WUtil.escape(d.dept)}" placeholder="例如：心内科" />
      <label class="field-label" for="req_date">期望日期 <em>*</em></label><input type="date" class="fg-input draft-field" id="req_date" data-draft="date" value="${WUtil.escape(d.date)}" />
      <div class="field-label">服务类型 <em>*</em></div><div class="service-choice">${PriceTable.items.filter(p=>p.active!==false).map(p=>`<button class="${d.serviceType===p.name?'selected':''}" data-service="${WUtil.escape(p.name)}"><span>${WUtil.escape(p.name)}</span><strong>¥${p.price}<small>/${WUtil.escape(p.unit)}</small></strong><small>${WUtil.escape(p.desc)}</small></button>`).join('')}</div>
      <label class="field-label" for="req_note">特殊照护需求</label><textarea class="fg-input draft-field" id="req_note" data-draft="note" rows="3" placeholder="例如：需要轮椅、老人耳背">${WUtil.escape(d.note)}</textarea>
    </section>
    <section class="card" id="identity_section"><div class="card-title">${P_ICON.card} 身份证资料 <span class="optional-tag">可后补</span></div><p class="privacy-note">仅用于实名认证。本原型数据保存在当前浏览器，请勿上传真实敏感证件。</p><div id="identityArea">${Patient.renderIdentityArea()}</div></section>
    <section class="card" id="report_section"><div class="card-title">${P_ICON.image} 检查报告 <span class="optional-tag">可选</span></div><p class="helper-text">JPEG、PNG、WebP，最多 6 张；原图单张不超过 10MB。</p><div id="reportArea">${Patient.renderReportArea()}</div></section>
    <section class="card final-preview"><div class="card-title">费用确认</div><div class="price-line"><span id="finalService">${WUtil.escape(d.serviceType)}</span><strong id="finalPrice">¥${PriceTable.getPrice(d.serviceType)}</strong></div><p>提交后管理员会收到新需求提醒。身份证和检查资料可稍后继续补充。</p><button class="btn" onclick="Patient.openFinalConfirm()">核对并提交需求</button></section>`;
  el.querySelectorAll('.draft-field').forEach(f=>f.addEventListener('change',()=>CareStore.patchDraft({[f.dataset.draft]:f.value.trim()})));
  el.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{CareStore.patchDraft({serviceType:b.dataset.service});Patient.renderNeed(el);});
};
Patient.renderIdentityArea = function() {
  const identity=CareStore.draft().identity;
  const side=(key,label)=>{const img=identity[key];return `<div class="identity-side"><div class="identity-preview">${img?`<img src="${img.dataUrl}" alt="身份证${label}" />`:`${P_ICON.card}<span>${label}</span>`}</div><input hidden type="file" id="id_${key}" accept="image/jpeg,image/png,image/webp" capture="environment" onchange="Patient.uploadIdentity('${key}',this)" /><button class="btn btn-outline btn-sm" onclick="document.getElementById('id_${key}').click()">${img?'重新上传':'上传'+label}</button>${img?`<button class="text-danger" onclick="Patient.removeIdentity('${key}')">删除</button><button class="btn btn-outline btn-sm" onclick="Patient.runOcr('${key}')">演示 OCR</button>`:''}</div>`};
  const f=identity.fields||{};
  return `<div class="identity-grid">${side('front','人像面')}${side('back','国徽面')}</div>${Object.keys(f).length?`<div class="ocr-result"><div class="ocr-demo-label">演示识别结果 · 请人工核对</div><label>姓名<input id="ocr_name" value="${WUtil.escape(f.name)}" /></label><label>身份证号<input id="ocr_number" value="${WUtil.escape(f.idNumber)}" /></label><label>性别<input id="ocr_gender" value="${WUtil.escape(f.gender)}" /></label><label>出生日期<input id="ocr_birth" value="${WUtil.escape(f.birthDate)}" /></label><button class="btn btn-sm" onclick="Patient.confirmIdentity()">确认识别信息</button><span class="identity-status">${identity.status==='confirmed'?'已确认':'待确认'}</span></div>`:''}`;
};
Patient.uploadIdentity=async function(side,input){const file=input.files?.[0];if(!file)return;try{this.toast('正在压缩图片…');const item=await MediaService.process(file);const identity=CareStore.draft().identity;CareStore.patchDraft({identity:{...identity,[side]:item,status:'unconfirmed'}});document.getElementById('identityArea').innerHTML=this.renderIdentityArea();}catch(e){this.toast(e.message);}input.value='';};
Patient.removeIdentity=function(side){const identity=CareStore.draft().identity;CareStore.patchDraft({identity:{...identity,[side]:null,status:'unconfirmed'}});document.getElementById('identityArea').innerHTML=this.renderIdentityArea();};
Patient.runOcr=async function(side){const identity=CareStore.draft().identity;if(!identity[side])return this.toast('请先上传图片');this.toast('正在进行演示识别…');const result=await IdentityOcrService.recognize({file:identity[side],side});if(!result.success)return this.toast(result.error);CareStore.patchDraft({identity:{...identity,fields:{...(identity.fields||{}),...result.fields},status:'unconfirmed'}});document.getElementById('identityArea').innerHTML=this.renderIdentityArea();this.toast('演示识别完成，请核对并确认');};
Patient.confirmIdentity=function(){const identity=CareStore.draft().identity;const fields={...(identity.fields||{}),name:WUtil.value('ocr_name'),idNumber:WUtil.value('ocr_number'),gender:WUtil.value('ocr_gender'),birthDate:WUtil.value('ocr_birth')};if(!fields.name||!/^[0-9Xx]{18}$/.test(fields.idNumber||''))return this.toast('请核对姓名和18位身份证号');CareStore.patchDraft({identity:{...identity,fields,status:'confirmed'}});document.getElementById('identityArea').innerHTML=this.renderIdentityArea();this.toast('身份证信息已确认');};
Patient.renderReportArea=function(){const imgs=CareStore.draft().reportImages||[];return `${WUtil.imageGrid(imgs,'Patient.removeReportImage')}<input hidden type="file" id="report_input_v2" accept="image/jpeg,image/png,image/webp" multiple onchange="Patient.uploadReportImages(this)" /><button class="btn btn-outline" ${imgs.length>=6?'disabled':''} onclick="document.getElementById('report_input_v2').click()">${imgs.length?'继续添加':'上传检查报告'}（${imgs.length}/6）</button>`;};
Patient.uploadReportImages=async function(input){const existing=[...(CareStore.draft().reportImages||[])],files=[...(input.files||[])];if(existing.length+files.length>6){this.toast('检查报告最多上传 6 张');input.value='';return;}for(const file of files){try{existing.push(await MediaService.process(file));}catch(e){this.toast(`${file.name}：${e.message}`);}}CareStore.patchDraft({reportImages:existing});document.getElementById('reportArea').innerHTML=this.renderReportArea();input.value='';};
Patient.removeReportImage=function(i){const imgs=[...(CareStore.draft().reportImages||[])];imgs.splice(i,1);CareStore.patchDraft({reportImages:imgs});document.getElementById('reportArea').innerHTML=this.renderReportArea();};
Patient.openFinalConfirm=function(){document.querySelectorAll('.draft-field').forEach(f=>CareStore.patchDraft({[f.dataset.draft]:f.value.trim()}));const d=CareStore.draft(),p=PriceTable.items.find(x=>x.name===d.serviceType);const missing=[['hospital','医院'],['dept','科室'],['date','日期']].filter(([k])=>!d[k]);if(missing.length){this.toast(`请补充：${missing.map(x=>x[1]).join('、')}`);document.getElementById('req_'+missing[0][0])?.focus();return;}WUtil.sheet('finalConfirmSheet','确认并提交',`<dl class="confirm-list"><div><dt>医院</dt><dd>${WUtil.escape(d.hospital)}</dd></div><div><dt>科室</dt><dd>${WUtil.escape(d.dept)}</dd></div><div><dt>日期</dt><dd>${WUtil.escape(d.date)}</dd></div><div><dt>服务</dt><dd>${WUtil.escape(d.serviceType)}</dd></div></dl><div class="confirm-total"><span>服务费用</span><strong>¥${p.price}<small>/${WUtil.escape(p.unit)}</small></strong></div><label class="consent-row"><input type="checkbox" id="privacyConsent" /> 我已核对信息，并了解敏感资料用途</label>`,`<button class="btn btn-outline" onclick="WUtil.closeSheet('finalConfirmSheet')">返回修改</button><button class="btn" onclick="Patient.submitConfirmedNeed()">确认提交</button>`);};
Patient.submitConfirmedNeed=function(){if(!document.getElementById('privacyConsent')?.checked)return this.toast('请先勾选信息确认与资料用途说明');try{const need=CareStore.createNeedFromDraft();WUtil.closeSheet('finalConfirmSheet');this.toast(`需求已提交，编号 ${need.id}`);setTimeout(()=>App.switchTab(2),700);}catch(e){this.toast(e.message);}};

Patient.renderProgress=function(el){const needs=CareStore.state.needs.filter(n=>n.patientName===MockData.patient.user.name);const flow=['待处理','已分配','服务中','已完成'];el.innerHTML=`<div class="page-head"><h2>陪诊进度</h2><div>关键状态变化会在顶部提醒您</div></div>${needs.length?needs.map(n=>{const idx=Math.max(0,flow.indexOf(n.status));return `<button class="need-card card" onclick="Patient.openNeedDetail('${n.id}')"><div><span class="status-badge ${WUtil.statusClass(n.status)}">${n.status}</span><small>${WUtil.escape(n.id)}</small></div><h3>${WUtil.escape(n.hospital)}</h3><p>${WUtil.escape(n.dept)} · ${WUtil.escape(n.date)} · ¥${n.serviceSnapshot?.price||n.amount}</p><div class="step-bar">${flow.map((s,i)=>`<span class="step ${i<idx?'done':''} ${i===idx?'active':''}"></span>`).join('')}</div>${n.escortReportId?'<strong class="report-ready">陪诊报告已发布 · 点击查看</strong>':''}</button>`;}).join(''):`<div class="empty"><div class="em-icon">${P_ICON.inbox}</div><p>暂无需求</p><button class="btn btn-sm" onclick="App.switchTab(1)">提交需求</button></div>`}`;};
Patient.openNeedDetail=function(id){const n=CareStore.need(id);if(!n)return this.toast('需求不存在');const r=CareStore.reportForNeed(id);const identity=n.identity||{};const reportHtml=r?.status==='published'?`<section class="card escort-report"><div class="card-title">${P_ICON.clipboard} 陪诊报告</div><div class="report-published">发布于 ${WUtil.escape(r.publishedAt)}</div><h4>服务时间线</h4><ol>${(r.timeline||[]).map(x=>`<li><time>${WUtil.escape(x.time)}</time><span>${WUtil.escape(x.text)}</span></li>`).join('')}</ol><h4>已办事项</h4><div class="report-tags">${(r.completedItems||[]).map(x=>`<span>${WUtil.escape(x)}</span>`).join('')}</div><h4>陪诊总结</h4><p>${WUtil.escape(r.summary)}</p><h4>注意事项</h4><p>${WUtil.escape(r.notes||'无')}</p>${WUtil.imageGrid(r.images)}<div class="plain-explanation"><strong>通俗说明</strong><p>${WUtil.escape(r.plainExplanation)}</p><small>仅作信息整理，以医生意见为准。</small></div></section>`:n.status==='已完成'?'<section class="card"><div class="card-title">陪诊报告</div><p class="helper-text">服务已完成，工作人员正在整理报告。</p></section>':'';document.getElementById('screen').innerHTML=`<div class="order-page"><div class="order-header"><button class="icon-button" onclick="App.switchTab(2)" aria-label="返回">${P_ICON.chevronLeft}</button><h2>需求详情</h2></div><section class="card"><span class="status-badge ${WUtil.statusClass(n.status)}">${n.status}</span><div class="summary-grid"><div><span>医院</span><strong>${WUtil.escape(n.hospital)}</strong></div><div><span>科室</span><strong>${WUtil.escape(n.dept)}</strong></div><div><span>日期</span><strong>${WUtil.escape(n.date)}</strong></div><div><span>费用</span><strong>¥${n.serviceSnapshot?.price||n.amount}</strong></div></div></section>${n.escortName?`<section class="card"><div class="card-title">${P_ICON.user} 陪诊师</div><p>${WUtil.escape(n.escortName)} · ${WUtil.escape(n.escortPhone)}</p></section>`:''}<section class="card"><div class="card-title">资料状态</div><p>身份证：${identity.front||identity.back?(identity.status==='confirmed'?'已上传并确认':'已上传，待确认'):'未上传'}</p><p>检查报告：${n.reportImages?.length||0} 张</p></section>${reportHtml}</div>`;};

Patient.renderHospitals=function(el){const apps=CareStore.state.hospitalApplications.filter(a=>a.patientName===MockData.patient.user.name);el.innerHTML=`<div class="page-head"><h2>医院介绍</h2><div>简介由管理员维护，具体就诊安排以医院通知为准</div></div><section class="card apply-hospital"><div class="card-title">${P_ICON.inbox} 没有想去的医院？</div><button class="btn btn-outline" onclick="Patient.toggleHospitalApply()">${this._showApplyForm?'收起申请':'申请新增医院'}</button></section>${this._showApplyForm?this._renderHospitalApplyForm():''}${apps.length?`<section class="card"><div class="card-title">我的医院申请</div>${apps.map(a=>`<div class="application-row"><div><strong>${WUtil.escape(a.hospital)}</strong><small>${WUtil.escape(a.dept)} · ${WUtil.escape(a.time)}</small>${a.rejectReason?`<p>原因：${WUtil.escape(a.rejectReason)}</p>`:''}</div><span class="status-badge ${a.status==='待审批'?'pending':a.status==='已通过'?'done':'cancelled'}">${a.status}</span></div>`).join('')}</section>`:''}${CareStore.state.hospitals.filter(h=>h.active).map(h=>`<article class="card hospital-intro"><div><h3>${WUtil.escape(h.name)}</h3><span>${WUtil.escape(h.level)}</span></div><p class="address">${P_ICON.mapPin} ${WUtil.escape(h.address||'地址待完善')}</p><p>${WUtil.escape(h.intro)}</p><dl><div><dt>优势科室</dt><dd>${WUtil.escape(h.specialties)}</dd></div><div><dt>咨询电话</dt><dd>${WUtil.escape(h.phone||'以医院官网为准')}</dd></div></dl></article>`).join('')}`;};
Patient._renderHospitalApplyForm=function(){return `<section class="card"><div class="card-title">申请新增医院</div><label class="field-label" for="apply_hospital">医院全称 <em>*</em></label><input id="apply_hospital" class="fg-input" /><label class="field-label" for="apply_dept">科室 <em>*</em></label><input id="apply_dept" class="fg-input" /><label class="field-label" for="apply_reason">申请原因 <em>*</em></label><textarea id="apply_reason" class="fg-input" rows="3"></textarea><button class="btn" onclick="Patient.submitHospitalApply()">提交后台审批</button></section>`;};
Patient.submitHospitalApply=function(){const hospital=WUtil.value('apply_hospital'),dept=WUtil.value('apply_dept'),reason=WUtil.value('apply_reason');if(!hospital||!dept||!reason)return this.toast('请完整填写医院、科室和申请原因');const r=CareStore.submitHospitalApplication({hospital,dept,reason,patientName:MockData.patient.user.name,patientPhone:MockData.patient.user.phone});this._showApplyForm=false;this.toast(r.duplicate?'相同医院申请正在审核中':'申请已提交，管理员已收到提醒');this.renderHospitals(document.getElementById('screen'));};

// ---- 管理端：菜单、通知、状态流转、审批、收费和报告 ----
Admin.menus=[{group:'运营总览',items:[{id:'dashboard',name:'工作台',icon:ICON.dashboard},{id:'track',name:'服务跟踪',icon:ICON.track},{id:'pricing',name:'服务收费',icon:ICON.finance}]},{group:'业务管理',items:[{id:'patients',name:'患者档案',icon:ICON.patients},{id:'needs',name:'需求处理',icon:ICON.needs},{id:'escorts',name:'陪诊师管理',icon:ICON.escorts},{id:'hospitals',name:'医院审批与资料',icon:ICON.hospitals}]},{group:'系统',items:[{id:'reviews',name:'评价反馈',icon:ICON.reviews},{id:'system',name:'系统设置',icon:ICON.system}]}];
const _legacyAdminRenderContent=Admin.renderContent.bind(Admin);
Admin.renderContent=function(){if(this.currentMenu==='pricing'){document.getElementById('atCrumb').textContent='服务收费';this.renderPricing(document.getElementById('adminContent'));return;} _legacyAdminRenderContent();};
Admin.renderNeeds=function(el){const statuses=['all','待处理','已分配','服务中','已完成','已取消'];el.innerHTML=`<div class="page-head"><h2>需求处理</h2><div>患者提交的需求统一在此处理，状态按服务实际进度推进</div></div><div class="filter-bar">${statuses.map((s,i)=>`<button class="filter-btn ${i===0?'active':''}" data-status="${s}">${s==='all'?`全部（${CareStore.state.needs.length}）`:s}</button>`).join('')}</div><div id="needsListV2"></div>`;const render=status=>{el.querySelectorAll('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.status===status));this.renderNeedsListV2(status);};el.querySelectorAll('.filter-btn').forEach(b=>b.onclick=()=>render(b.dataset.status));render('all');};
Admin.renderNeedsListV2=function(status){const list=status==='all'?CareStore.state.needs:CareStore.state.needs.filter(n=>n.status===status);const host=document.getElementById('needsListV2');host.innerHTML=list.length?`<div class="table-card"><table class="data-table"><thead><tr><th>患者</th><th>需求</th><th>提交时间</th><th>陪诊师</th><th>状态</th><th>操作</th></tr></thead><tbody>${list.map(n=>`<tr><td><strong>${WUtil.escape(n.patientName)}</strong><div class="cp-sub">${WUtil.escape(n.phone)}</div></td><td><strong>${WUtil.escape(n.hospital)}</strong><div class="cp-sub">${WUtil.escape(n.dept)} · ${WUtil.escape(n.date)} · ${WUtil.escape(n.serviceType)}</div></td><td>${WUtil.escape(n.createTime)}<div class="cp-sub">${WUtil.escape(n.id)}</div></td><td>${WUtil.escape(n.escortName||'待分配')}</td><td><span class="status-badge ${WUtil.statusClass(n.status)}">${n.status}</span></td><td><button class="btn-link" onclick="Admin.openNeed('${n.id}')">处理</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-inline">暂无对应需求</div>';};
Admin.renderTrack=function(el){const active=CareStore.state.needs.filter(n=>['已分配','服务中'].includes(n.status));el.innerHTML=`<div class="page-head"><h2>服务跟踪</h2><div>查看已分配和正在服务的需求</div></div><div class="kpi-grid"><div class="kpi-card kpi-warn"><div class="kpi-icon">${ICON.escorts}</div><div class="kpi-body"><div class="kpi-num">${active.filter(n=>n.status==='已分配').length}</div><div class="kpi-label">已分配待开始</div></div></div><div class="kpi-card kpi-blue"><div class="kpi-icon">${ICON.track}</div><div class="kpi-body"><div class="kpi-num">${active.filter(n=>n.status==='服务中').length}</div><div class="kpi-label">服务中</div></div></div></div>${active.length?`<div class="table-card"><table class="data-table"><thead><tr><th>患者</th><th>医院/科室</th><th>陪诊师</th><th>状态</th><th>操作</th></tr></thead><tbody>${active.map(n=>`<tr><td>${WUtil.escape(n.patientName)}</td><td>${WUtil.escape(n.hospital)}<div class="cp-sub">${WUtil.escape(n.dept)} · ${WUtil.escape(n.date)}</div></td><td>${WUtil.escape(n.escortName||'-')}</td><td><span class="status-badge ${WUtil.statusClass(n.status)}">${n.status}</span></td><td><button class="btn-link" onclick="Admin.openNeed('${n.id}')">详情</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-inline">暂无进行中的服务</div>'}`;};
Admin.renderNotifyPanel=function(){const panel=document.getElementById('notifyPanel');if(!panel)return;const list=CareStore.notificationsFor('admin');panel.style.display='block';panel.innerHTML=`<div class="notify-panel-head"><h4>通知提醒</h4><button class="btn-link" onclick="Admin.markAllNotifyRead()">全部已读</button></div>${list.length?list.map(n=>`<button class="notify-item ${n.read?'':'unread'}" onclick="Admin.openNotification('${n.id}')"><span class="notify-dot"></span><span><span class="notify-item-text">${WUtil.escape(n.title)}</span><small class="notify-item-time">${WUtil.escape(n.time)}</small></span></button>`).join(''):'<div class="empty-inline">暂无通知</div>'}`;};
Admin.openNotification=function(id){const n=CareStore.markNotification(id);this.refreshNotifyBadge();document.getElementById('notifyPanel').style.display='none';if(n?.targetType==='need'&&CareStore.need(n.targetId)){this.switchMenu('needs');setTimeout(()=>this.openNeed(n.targetId),0);}else if(n?.targetType==='hospitalApplication'){this.switchMenu('hospitals');}else this.toast('对应记录不存在或已移除');};
Admin.markAllNotifyRead=function(){CareStore.markAllNotifications('admin');this.renderNotifyPanel();this.refreshNotifyBadge();};

Admin.openNeed=function(id){const n=CareStore.need(id);if(!n)return this.toast('需求不存在');const recommended=MockData.escorts.filter(e=>e.status==='空闲'||e.name===n.escortName).slice(0,3);const identity=n.identity||{};const report=CareStore.reportForNeed(id);this.modal(`<div class="modal-head-row"><h2>需求详情</h2><span class="status-badge ${WUtil.statusClass(n.status)}">${n.status}</span></div><div class="cp-sub">编号 ${WUtil.escape(n.id)} · ${WUtil.escape(n.createTime)}</div><div class="modal-grid-2"><section class="modal-card"><div class="card-title">${ICON.user} 患者</div><div class="pb-row"><span class="pb-label">姓名</span><span class="pb-value">${WUtil.escape(n.patientName)}</span></div><div class="pb-row"><span class="pb-label">电话</span><span class="pb-value">${WUtil.escape(n.phone)}</span></div><div class="pb-row"><span class="pb-label">身份证</span><span class="pb-value">${CareStore.maskId(identity.fields?.idNumber)}</span></div></section><section class="modal-card"><div class="card-title">${ICON.clipboard} 服务</div><div class="pb-row"><span class="pb-label">医院</span><span class="pb-value">${WUtil.escape(n.hospital)}</span></div><div class="pb-row"><span class="pb-label">科室/日期</span><span class="pb-value">${WUtil.escape(n.dept)} · ${WUtil.escape(n.date)}</span></div><div class="pb-row"><span class="pb-label">价格快照</span><span class="pb-value">¥${n.serviceSnapshot?.price||n.amount}/${WUtil.escape(n.serviceSnapshot?.unit||'次')}</span></div></section></div><section class="modal-card"><div class="card-title">${ICON.fileText} 已上传资料</div><p>身份证：${identity.front||identity.back?(identity.status==='confirmed'?'已确认':'待患者确认'):'未上传'}；检查报告：${n.reportImages?.length||0} 张</p>${WUtil.imageGrid(n.reportImages||[])}</section>${n.status==='待处理'?`<section class="modal-card"><div class="card-title">${ICON.escorts} 分配陪诊师</div>${recommended.map(e=>`<button class="escort-pick" onclick="Admin.assignEscortV2('${n.id}','${e.id}')"><span class="ep-avatar">${WUtil.escape(e.avatar)}</span><span class="ep-info"><strong>${WUtil.escape(e.name)}</strong><small>${WUtil.escape(e.tags.slice(0,3).join(' · '))}</small></span><span>选择</span></button>`).join('')}</section><button class="btn btn-outline" onclick="Admin.cancelNeedV2('${n.id}')">取消需求</button>`:''}${n.status==='已分配'?`<section class="modal-card"><div class="card-title">已分配陪诊师</div><p>${WUtil.escape(n.escortName)} · ${WUtil.escape(n.escortPhone)}</p></section><button class="btn" onclick="Admin.startServiceV2('${n.id}')">开始服务</button>`:''}${n.status==='服务中'?`<button class="btn" onclick="Admin.finishServiceV2('${n.id}')">完成服务</button>`:''}${n.status==='已完成'?`<section class="modal-card"><div class="card-title">${ICON.fileText} 陪诊报告</div><p>${report?.status==='published'?'已发布给患者':'尚未发布'}</p><button class="btn" onclick="Admin.openReportEditor('${n.id}')">${report?'编辑报告':'填写并发布报告'}</button></section>`:''}`);};
Admin.assignEscortV2=function(needId,escortId){const e=MockData.escorts.find(x=>x.id===escortId);try{CareStore.transitionNeed(needId,'已分配',{escortName:e.name,escortPhone:e.phone});e.status='服务中';this.closeModal();this.toast('陪诊师已分配，患者已收到提醒');this.renderContent();}catch(err){this.toast(err.message);}};
Admin.startServiceV2=function(id){try{CareStore.transitionNeed(id,'服务中');this.closeModal();this.toast('服务已开始，患者已收到提醒');this.renderContent();}catch(e){this.toast(e.message);}};
Admin.finishServiceV2=function(id){try{CareStore.transitionNeed(id,'已完成');this.closeModal();this.toast('服务已完成，请填写陪诊报告');this.renderContent();setTimeout(()=>this.openReportEditor(id),100);}catch(e){this.toast(e.message);}};
Admin.cancelNeedV2=function(id){if(!confirm('确认取消该需求？'))return;try{CareStore.transitionNeed(id,'已取消');this.closeModal();this.renderContent();}catch(e){this.toast(e.message);}};

Admin.openReportEditor=function(needId){this.closeModal();const r=CareStore.reportForNeed(needId)||{timeline:[],completedItems:[],summary:'',notes:'',images:[],plainExplanation:''};this._reportImages=[...(r.images||[])];this.modal(`<div class="modal-head-row"><h2>陪诊报告</h2><span class="status-badge ${r.status==='published'?'done':'pending'}">${r.status==='published'?'已发布':'草稿'}</span></div><p class="helper-text">原始内容与通俗说明会同时展示给患者。请勿在通俗说明中添加诊断或用药决定。</p><label class="field-label" for="er_timeline">服务时间线</label><textarea id="er_timeline" class="fg-input" rows="4" placeholder="每行一项，例如：08:30 | 与患者会合">${WUtil.escape((r.timeline||[]).map(x=>`${x.time} | ${x.text}`).join('\n'))}</textarea><label class="field-label" for="er_items">已办事项</label><input id="er_items" class="fg-input" value="${WUtil.escape((r.completedItems||[]).join('、'))}" placeholder="挂号、问诊、取药" /><label class="field-label" for="er_summary">陪诊总结 <em>*</em></label><textarea id="er_summary" class="fg-input" rows="3">${WUtil.escape(r.summary)}</textarea><label class="field-label" for="er_notes">就医注意事项</label><textarea id="er_notes" class="fg-input" rows="3">${WUtil.escape(r.notes)}</textarea><label class="field-label" for="er_plain">给患者的通俗说明</label><textarea id="er_plain" class="fg-input" rows="3" placeholder="留空则按总结生成规则模板">${WUtil.escape(r.plainExplanation)}</textarea><div class="field-label">报告图片（最多 6 张）</div><div id="escortReportImages">${this.renderReportImages()}</div><input hidden type="file" id="er_image_input" multiple accept="image/jpeg,image/png,image/webp" onchange="Admin.addReportImages(this)" /><button class="btn btn-outline" onclick="document.getElementById('er_image_input').click()">上传报告图片</button><div class="modal-foot"><button class="btn btn-outline" onclick="Admin.saveReport('${needId}',false)">保存草稿</button><button class="btn" onclick="Admin.saveReport('${needId}',true)">发布给患者</button></div>`);};
Admin.renderReportImages=function(){return WUtil.imageGrid(this._reportImages||[],'Admin.removeReportImage');};
Admin.addReportImages=async function(input){const files=[...(input.files||[])];if((this._reportImages?.length||0)+files.length>6){this.toast('报告图片最多 6 张');input.value='';return;}for(const f of files){try{this._reportImages.push(await MediaService.process(f));}catch(e){this.toast(`${f.name}：${e.message}`);}}document.getElementById('escortReportImages').innerHTML=this.renderReportImages();input.value='';};
Admin.removeReportImage=function(i){this._reportImages.splice(i,1);document.getElementById('escortReportImages').innerHTML=this.renderReportImages();};
Admin.saveReport=function(needId,publish){const timeline=WUtil.value('er_timeline').split('\n').filter(Boolean).map(line=>{const parts=line.split('|');return {time:(parts.shift()||'').trim(),text:parts.join('|').trim()||line.trim()};});const data={timeline,completedItems:WUtil.value('er_items').split(/[、,，]/).map(x=>x.trim()).filter(Boolean),summary:WUtil.value('er_summary'),notes:WUtil.value('er_notes'),plainExplanation:WUtil.value('er_plain'),images:this._reportImages||[]};try{CareStore.saveEscortReport(needId,data,publish);this.closeModal();this.toast(publish?'陪诊报告已发布，患者已收到提醒':'报告草稿已保存');this.renderContent();}catch(e){this.toast(e.message);}};

Admin.renderHospitals=function(el){const pending=CareStore.state.hospitalApplications.filter(a=>a.status==='待审批'),handled=CareStore.state.hospitalApplications.filter(a=>a.status!=='待审批');el.innerHTML=`<div class="page-head"><h2>医院审批与资料</h2><div>仅审批患者提出的新医院，并维护患者端可见介绍</div></div><section class="db-card"><div class="db-card-head"><h3>${ICON.clipboard} 待审批（${pending.length}）</h3></div><div class="db-card-body">${pending.length?pending.map(a=>`<div class="approval-card"><div><strong>${WUtil.escape(a.hospital)}</strong><p>${WUtil.escape(a.patientName)} · ${WUtil.escape(a.dept)} · ${WUtil.escape(a.reason)}</p><small>${WUtil.escape(a.time)}</small></div><div><button class="btn btn-sm" onclick="Admin.approveHospitalV2('${a.id}')">通过</button><button class="btn btn-outline btn-sm" onclick="Admin.rejectHospitalV2('${a.id}')">驳回</button></div></div>`).join(''):'<div class="empty-inline">暂无待审批申请</div>'}</div></section><section class="db-card"><div class="db-card-head"><h3>${ICON.building} 医院资料（${CareStore.state.hospitals.length}）</h3></div><div class="db-card-body"><div class="hospital-grid">${CareStore.state.hospitals.map(h=>`<article class="hospital-card"><div class="hc-head"><div><div class="hc-name">${WUtil.escape(h.name)}</div><div class="hc-sub">${WUtil.escape(h.level)} · ${WUtil.escape(h.address||'地址待完善')}</div></div></div><div class="hc-body"><p>${WUtil.escape(h.intro)}</p><div class="pb-row"><span class="pb-label">优势科室</span><span class="pb-value">${WUtil.escape(h.specialties)}</span></div></div><button class="btn btn-outline btn-sm" onclick="Admin.editHospitalV2('${h.id}')">编辑患者端介绍</button></article>`).join('')}</div></div></section><section class="db-card"><div class="db-card-head"><h3>审批记录</h3></div><div class="db-card-body">${handled.map(a=>`<div class="application-row"><div><strong>${WUtil.escape(a.hospital)}</strong><small>${WUtil.escape(a.patientName)} · ${WUtil.escape(a.handledAt||a.time)}</small>${a.rejectReason?`<p>${WUtil.escape(a.rejectReason)}</p>`:''}</div><span class="status-badge ${a.status==='已通过'?'done':'cancelled'}">${a.status}</span></div>`).join('')||'<div class="empty-inline">暂无记录</div>'}</div></section>`;};
Admin.approveHospitalV2=function(id){try{CareStore.approveHospitalApplication(id);this.toast('医院申请已通过，患者已收到提醒');this.renderContent();}catch(e){this.toast(e.message);}};
Admin.rejectHospitalV2=function(id){const reason=prompt('请填写驳回原因（患者可见）：');if(reason===null)return;try{CareStore.rejectHospitalApplication(id,reason);this.toast('已驳回并通知患者');this.renderContent();}catch(e){this.toast(e.message);}};
Admin.editHospitalV2=function(id){const h=CareStore.state.hospitals.find(x=>x.id===id);if(!h)return;const level=prompt('医院等级：',h.level);if(level===null)return;const address=prompt('医院地址：',h.address);if(address===null)return;const specialties=prompt('优势科室：',h.specialties);if(specialties===null)return;const intro=prompt('患者端简介：',h.intro);if(intro===null)return;Object.assign(h,{level:level.trim(),address:address.trim(),specialties:specialties.trim(),intro:intro.trim()});CareStore.save();this.toast('医院介绍已更新，患者端已同步');this.renderContent();};

Admin.renderPricing=function(el){const changes=CareStore.state.priceChanges;el.innerHTML=`<div class="page-head"><h2>服务收费</h2><div>仅维护患者端公开价格；历史需求保留提交时价格快照</div></div><div class="kpi-grid"><div class="kpi-card kpi-blue"><div class="kpi-icon">${ICON.finance}</div><div class="kpi-body"><div class="kpi-num">${PriceTable.items.length}</div><div class="kpi-label">在售服务</div></div></div><div class="kpi-card kpi-warn"><div class="kpi-icon">${ICON.scroll}</div><div class="kpi-body"><div class="kpi-num">${changes.length}</div><div class="kpi-label">价格变更记录</div></div></div></div><section class="db-card"><div class="db-card-head"><h3>公开价格表</h3></div><div class="table-card"><table class="data-table"><thead><tr><th>服务</th><th>说明</th><th>计价单位</th><th>公开价格</th><th>操作</th></tr></thead><tbody>${PriceTable.items.map(p=>`<tr><td><strong>${WUtil.escape(p.name)}</strong></td><td>${WUtil.escape(p.desc)}</td><td>${WUtil.escape(p.unit)}</td><td><input class="fg-input price-input" type="number" min="1" id="price_${p.id}" value="${p.price}" /></td><td><button class="btn btn-sm" onclick="Admin.savePriceV2('${p.id}')">保存价格</button></td></tr>`).join('')}</tbody></table></div></section><section class="db-card"><div class="db-card-head"><h3>最近变更</h3></div><div class="db-card-body">${changes.slice(0,10).map(c=>`<div class="db-row-item"><div><strong>${WUtil.escape(c.itemName)}</strong><p class="dbr-info">¥${c.oldPrice} → ¥${c.newPrice} · ${WUtil.escape(c.time)}</p></div><span class="status-badge done">已生效</span></div>`).join('')||'<div class="empty-inline">暂无变更</div>'}</div></section>`;};
Admin.savePriceV2=function(id){const value=Number(document.getElementById('price_'+id)?.value);const item=CareStore.state.prices.find(p=>p.id===id);if(!item||!Number.isFinite(value)||value<=0)return this.toast('请输入大于 0 的有效价格');if(item.price===value)return this.toast('价格没有变化');CareStore.updatePrice(id,value);this.toast('公开价格已更新，患者端立即生效');this.renderPricing(document.getElementById('adminContent'));};
Admin.renderSystem=function(el){el.innerHTML=`<div class="page-head"><h2>系统设置</h2><div>演示环境与数据安全说明</div></div><div class="setting-grid"><section class="modal-card"><div class="card-title">${ICON.cpu} AI 助手</div><div class="pb-row"><span class="pb-label">运行方式</span><span class="pb-value">本地规则状态机</span></div><div class="pb-row"><span class="pb-label">外部密钥</span><span class="pb-value">未在浏览器保存</span></div><p class="helper-text">正式接入大模型时必须使用后端代理，AI 不能绕过患者确认直接提交。</p></section><section class="modal-card"><div class="card-title">${ICON.shield} 数据范围</div><p>当前为单浏览器演示原型，图片和资料保存在 localStorage。请勿上传真实身份证或病历。</p><button class="btn btn-outline btn-sm" onclick="Admin.resetDemoData()">重置演示数据</button></section></div>`;};
Admin.resetDemoData=function(){if(!confirm('确认清空当前浏览器的演示数据并重新加载？'))return;localStorage.removeItem(CareStore.key);location.reload();};

// 兼容后台既有列表中的按钮调用，统一转到新状态机。
Admin.assignEscort=Admin.assignEscortV2; Admin.startService=Admin.startServiceV2; Admin.finishService=Admin.finishServiceV2; Admin.cancelNeed=Admin.cancelNeedV2;
